<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="UpdateEventTimeStampWithSystemTime" Id="{3d5b7336-b492-45ee-9bc3-4633563c28e5}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION UpdateEventTimeStampWithSystemTime
VAR_INPUT
	stEvent : REFERENCE TO ST_Event;
END_VAR
VAR
fbGETSYSTEMTIME : GETSYSTEMTIME;


stFileTime : T_FILETIME;

END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[fbGETSYSTEMTIME(timeLoDW => stFileTime.dwLowDateTime , 
				timeHiDW => stFileTime.dwHighDateTime);
				
stEvent.dtTimestamp := FILETIME_TO_DT(fileTime := stFileTime);]]></ST>
    </Implementation>
    <LineIds Name="UpdateEventTimeStampWithSystemTime">
      <LineId Id="7" Count="0" />
      <LineId Id="16" Count="0" />
      <LineId Id="21" Count="1" />
    </LineIds>
  </POU>
</TcPlcObject>